### ISSUE TITLE
`hydra-cli scaffold` not working

### ISSUE THREAD

**Issue by jamiehewitt15** [Joystream/hydra#216] opened 2021-02-15 18:09 UTC
I have been getting some issues with the `hydra-cli scaffold` command. It seems to get stuck part of the way through and then doesn't create the docker-compose.yml or package.json files, the mappings folder is also empty. I'm not getting any error messages, the command line just perpetually says `Scaffolding...`

I would suggest the first step here would be to add some additional error handling in order to give the user feedback on what the issue is. 

My system is:

- Windows 10 Home Edition, 64 bit.
- Docker version 20.10.2
- Node.js version v14.15.5
- npx version 6.14.11

**Comment by jamiehewitt15** [comment] 2021-02-18 15:57
After installing Ubuntu and running the same `hydra-cli scaffold` command it worked so it looks like this is a Windows only issue. We may need to add a warning to the readme to warn users that the hydra-cli is currently not supported on Windows

**Comment by dzhelezov** [comment] 2021-04-07 12:24
Node v14 is known to cause problems with hydra-cli.

**Comment by dzhelezov** [comment] 2021-04-07 12:27
possible duplicate of #351  Closing for now.

**Closed by dzhelezov** 2021-04-07 12:27 UTC
